---
IP: 127.0.0.1
Port: 9000

BindingsFolder: bindings
ActionManifestFile: thumbparams_actions.json
ActionSetHandle: "/actions/thumbparams"

ConnectedParam: VTP_Active

Params:
  LeftTrigger       : float:/in/lefttrigger
  RightTrigger      : float:/in/righttrigger
  LeftGrip          : float:/in/leftgrip
  RightGrip         : float:/in/rightgrip
  LeftTriggerTouch  : bool:/in/lefttriggertouch
  RightTriggerTouch : bool:/in/righttriggertouch
#  LeftAButton       : bool:/in/leftabutton
#  LeftBButton       : bool:/in/leftbbutton
#  LeftTrackPad      : bool:/in/lefttrackpad
#  LeftThumbStick    : bool:/in/leftstick
#  RightAButton      : bool:/in/rightabutton
#  RightBButton      : bool:/in/rightbbutton
#  RightTrackPad     : bool:/in/righttrackpad
#  RightThumbStick   : bool:/in/rightstick

CustomParams:
- OSCName: LeftThumb
  Expression: len(v) - ([True] + v)[::-1].index(True) # last index of true value, or zero
  Actions:
  - bool:/in/leftabutton
  - bool:/in/leftbbutton
  - bool:/in/lefttrackpad
  - bool:/in/leftstick
- OSCName: RightThumb
  Expression: len(v) - ([True] + v)[::-1].index(True) # last index of true value, or zero
  Actions:
  - bool:/in/rightabutton
  - bool:/in/rightbbutton
  - bool:/in/righttrackpad
  - bool:/in/rightstick
- OSCName: LeftThumbTouch
  Expression: any(v)
  Actions:
  - bool:/in/leftabutton
  - bool:/in/leftbbutton
  - bool:/in/lefttrackpad
  - bool:/in/leftstick
- OSCName: RightThumbTouch
  Expression: any(v)
  Actions:
  - bool:/in/rightabutton
  - bool:/in/rightbbutton
  - bool:/in/righttrackpad
  - bool:/in/rightstick
- OSCName: LeftABButtons
  Expression: v[0] and v[1]
  Actions:
  - bool:/in/leftabutton
  - bool:/in/leftbbutton
- OSCName: RightABButtons
  Expression: v[0] and v[1]
  Actions:
  - bool:/in/rightabutton
  - bool:/in/rightbbutton
- OSCName: RightGripSquareExample
  Expression: v[0]**2
  Actions:
  - float:/in/rightgrip
  Ignore: true
