---
IP: 127.0.0.1
Port: 9000

BindingsFolder: bindings
ActionManifestFile: thumbparams_actions.json
ActionSetHandle: /actions/VTP

ConnectedParam: VTP_Active

Params: 
  LeftTrigger       : left.trigger.pull
  RightTrigger      : right.trigger.pull
  LeftGrip          : left.grip.pull
  RightGrip         : right.grip.pull
  LeftTriggerTouch  : left.trigger.touch
  RightTriggerTouch : right.trigger.touch

CustomParams:
- OSCName: ControllerTipDistance
  Expression: glm.distance(v[0].position, v[1].position)
  Actions:
  - left.pose.tip
  - right.pose.tip
- OSCName: RightControllerToHeadDist
  Expression: glm.distance(v[0].position, v[1].position)
  Actions:
  - head.pose.raw
  - right.pose.tip
- OSCName: DistanceTip20cm
  # vector is 0.2m along the forward axis
  # transform using transform matrix for each controller and get distance between
  Expression: glm.distance(v[0].matrix * glm.vec4(0,0,-0.2,1), v[1].matrix * glm.vec4(0,0,-0.2,1))
  Actions:
  - right.pose.tip
  - left.pose.tip
- OSCName: HeadsetXPos
  Expression: v[0].position.x
  Actions:
  - head.pose.raw
##################################
- OSCName: LeftThumbTouch
  Expression: any(v)
  Actions:
  - left.a.touch
  - left.b.touch
  - left.trackpad.touch
  - left.joystick.touch
- OSCName: RightThumbTouch
  Expression: any(v)
  Actions:
  - right.a.touch
  - right.b.touch
  - right.trackpad.touch
  - right.joystick.touch
####################################
- OSCName: RightJoy.X
  Expression: v[0].x
  Actions:
  - right.joystick.position
- OSCName: RightJoy.Y
  Expression: v[0].y
  Actions:
  - right.joystick.position
