---
IP: 127.0.0.1
Port: 9000

BindingsFolder: bindings
ActionManifestFile: thumbparams_actions.json
ActionSetHandle: "/actions/thumbparams"

ConnectedParam: VTP_Active

FloatParams:
- OSCName: LeftTrigger
  Action: "/actions/thumbparams/in/lefttrigger"
- OSCName: RightTrigger
  Action: "/actions/thumbparams/in/righttrigger"
- OSCName: LeftGrip
  Action: "/actions/thumbparams/in/leftgrip"
- OSCName: RightGrip
  Action: "/actions/thumbparams/in/rightgrip"

BoolParams:
- OSCName: LeftAButton
  Action: "/actions/thumbparams/in/leftabutton"
  Ignore: true
- OSCName: LeftBButton
  Action: "/actions/thumbparams/in/leftbbutton"
  Ignore: true
- OSCName: LeftTrackPad
  Action: "/actions/thumbparams/in/lefttrackpad"
  Ignore: true
- OSCName: LeftThumbStick
  Action: "/actions/thumbparams/in/leftstick"
  Ignore: true
- OSCName: RightAButton
  Action: "/actions/thumbparams/in/rightabutton"
  Ignore: true
- OSCName: RightBButton
  Action: "/actions/thumbparams/in/rightbbutton"
  Ignore: true
- OSCName: RightTrackPad
  Action: "/actions/thumbparams/in/righttrackpad"
  Ignore: true
- OSCName: RightThumbStick
  Action: "/actions/thumbparams/in/rightstick"
  Ignore: true
- OSCName: LeftTriggerTouch
  Action: "/actions/thumbparams/in/lefttriggertouch"
- OSCName: RightTriggerTouch
  Action: "/actions/thumbparams/in/righttriggertouch"

CustomParams:
- OSCName: LeftThumb
  Expression: len(v) - ([True] + v)[::-1].index(True)
  Actions:
  - bool:/actions/thumbparams/in/leftabutton
  - bool:/actions/thumbparams/in/leftbbutton
  - bool:/actions/thumbparams/in/lefttrackpad
  - bool:/actions/thumbparams/in/leftstick
- OSCName: RightThumb
  Expression: len(v) - ([True] + v)[::-1].index(True)
  Actions:
  - bool:/actions/thumbparams/in/rightabutton
  - bool:/actions/thumbparams/in/rightbbutton
  - bool:/actions/thumbparams/in/righttrackpad
  - bool:/actions/thumbparams/in/rightstick
- OSCName: LeftThumbTouch
  Expression: any(v)
  Actions:
  - bool:/actions/thumbparams/in/leftabutton
  - bool:/actions/thumbparams/in/leftbbutton
  - bool:/actions/thumbparams/in/lefttrackpad
  - bool:/actions/thumbparams/in/leftstick
- OSCName: RightThumbTouch
  Expression: any(v)
  Actions:
  - bool:/actions/thumbparams/in/rightabutton
  - bool:/actions/thumbparams/in/rightbbutton
  - bool:/actions/thumbparams/in/righttrackpad
  - bool:/actions/thumbparams/in/rightstick
- OSCName: LeftABButtons
  Expression: v[0] and v[1]
  Actions:
  - bool:/actions/thumbparams/in/leftabutton
  - bool:/actions/thumbparams/in/leftbbutton
- OSCName: RightABButtons
  Expression: v[0] and v[1]
  Actions:
  - bool:/actions/thumbparams/in/rightabutton
  - bool:/actions/thumbparams/in/rightbbutton
- OSCName: RightGripSquareExample
  Expression: v[0]**2
  Actions:
  - float:/actions/thumbparams/in/rightgrip
  Ignore: true
